version: "3.9"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_db:/data/db
    ports:
      - 27017:27017 #necessary?

  server:
    ports:
      - 3001:3001
    links:
      - mongo
    depends_on:
      - mongo

  client:
    ports:
      - 3000:3000
    depends_on:
      - server
